Thuvien/Models/docgia.cs
namespace ThuVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("docgia")]
    public partial class docgia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public docgia()
        {
            muontras = new HashSet<muontra>();
            phieutams = new HashSet<phieutam>();
        }

        [Key]
        [StringLength(20)]
        public string sothe { get; set; }

        [StringLength(50)]
        public string password { get; set; }

        [StringLength(100)]
        public string tendocgia { get; set; }

        public DateTime? ngaysinh { get; set; }

        [StringLength(100)]
        public string diachi { get; set; }

        [StringLength(20)]
        public string sdt { get; set; }

        public bool? gioitinh { get; set; }

        public DateTime? ngaythem { get; set; }

        public bool? trangthai { get; set; }

        public int? maloaidocgia { get; set; }

        public DateTime? hanthe { get; set; }

        public double? tienthe { get; set; }

        [Column(TypeName = "text")]
        public string imgurl { get; set; }

        public virtual loaidocgia loaidocgia { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<muontra> muontras { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieutam> phieutams { get; set; }
    }
}

Thuvien/Areas/Admin/Controllers/DocgiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThuVien.Models;
using System.IO;

namespace ThuVien.Areas.Admin.Controllers
{
    public class DocgiaController : NguoidungController
    {
        ThuvienDbContext db = new ThuvienDbContext();
        // GET: Admin/Docgia
        public ActionResult Index()
        {
            ViewBag.maloaidocgia = new SelectList(db.loaidocgias, "maloaidocgia", "tenloai");
            var ds = db.docgias.ToList();

            return View(ds);
        }
        public ActionResult Deltai(string sothe)
        {
            docgia dg = db.docgias.Find(sothe);
            ViewBag.maloaidocgia = new SelectList(db.loaidocgias, "maloaidocgia", "tenloai", dg.maloaidocgia);
            if (dg.gioitinh == true)
            {
                ViewBag.nam = "selected";
            }
            if (dg.gioitinh == false)
            {
                ViewBag.nu = "selected";
            }
            if (dg.trangthai == true)
            {
                ViewBag.active = "selected";
            }
            if (dg.trangthai == false)
            {
                ViewBag.block = "selected";
            }

            DateTime ngay1 = DateTime.Now;
            DateTime ngay2 = Convert.ToDateTime(dg.hanthe);
            TimeSpan Time = ngay2 - ngay1;
            int day = Time.Days;
            if (day > 0)
            {
                ViewBag.ngayconlai = day.ToString()+" ngày";
            }
            else ViewBag.ngayconlai = "Thẻ hết hạn";
            return View(dg);
        }

        public JsonResult Get(string sothe)
        {
            var ds = db.docgias.Where(x => x.sothe == sothe).Select(x => new { sothe = x.sothe, tendocgia = x.tendocgia, ngaysinh = x.ngaysinh, diachi = x.diachi, sdt = x.sdt }).ToList().SingleOrDefault();
            return Json(new { success = true, dt = ds, timed = ds.ngaysinh.ToString() }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult Getcart(string sothe)
        {
            var ds = db.docgias.Where(x => x.sothe == sothe).Select(x => new { sothe = x.sothe }).ToList().SingleOrDefault();
            return Json(new { success = true, dt = ds }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Delete(string sothe)
        {
            docgia dg = db.docgias.Find(sothe);
            db.docgias.Remove(dg);
            var rs = db.SaveChanges();

            return Json(rs, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CapnhapCart(string sothe,double tienthe)
        {
            docgia dg = db.docgias.Find(sothe);
            //db.docgias.Remove(dg);
            if(dg.tienthe+tienthe<0)
            {
                return Json(new { error = false,ms="số tiền trừ lớn hơn số tiền hiện tại" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                dg.tienthe = dg.tienthe + tienthe;
                db.Entry(dg).State = System.Data.Entity.EntityState.Modified;
                var rs = db.SaveChanges();

                return Json(new { success=true, ms = "cập nhập thành công" }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]

        public ActionResult Create(int maloaidocgia, string tendocgia, DateTime ngaysinh, string diachi, string sdt, bool gioitinh, HttpPostedFileBase imgurl, bool trangthai)
        {
            docgia dg = new docgia();
            Random random = new Random();
        sothe:
            string st = "ST" + random.Next(1000, 2000).ToString();
            var ktdg = db.docgias.Find(st);
            if (ktdg != null)
            {
                goto sothe;
            }
            dg.sothe = st;
            dg.tendocgia = tendocgia;
            dg.maloaidocgia = maloaidocgia;
            dg.ngaysinh = ngaysinh;
            dg.diachi = diachi;
            dg.sdt = sdt;
            dg.gioitinh = gioitinh;

            dg.trangthai = trangthai;

            if (imgurl != null && imgurl.ContentLength > 0)
            {
                var filename = Path.GetFileName(imgurl.FileName);
                dg.imgurl = filename;
                var path = Path.Combine(Server.MapPath("~/Images/docgia/"), filename);
                imgurl.SaveAs(path);
            }
            dg.tienthe = 0;
            dg.ngaythem = DateTime.Now;
            dg.hanthe = dg.ngaythem.Value.AddYears(1);

            db.docgias.Add(dg);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]

        public ActionResult Edit(string sothe, int maloaidocgia, string tendocgia, DateTime ngaysinh, string diachi, string sdt, bool gioitinh, HttpPostedFileBase imgurl, bool trangthai)
        {
            docgia dg = db.docgias.Find(sothe);

            dg.tendocgia = tendocgia;
            dg.maloaidocgia = maloaidocgia;
            dg.ngaysinh = ngaysinh;
            dg.diachi = diachi;
            dg.sdt = sdt;
            dg.gioitinh = gioitinh;

            dg.trangthai = trangthai;

            if (imgurl != null && imgurl.ContentLength > 0)
            {
                var filename = Path.GetFileName(imgurl.FileName);
                dg.imgurl = filename;
                var path = Path.Combine(Server.MapPath("~/Images/docgia/"), filename);
                imgurl.SaveAs(path);
            }

            db.Entry(dg).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Deltai", new { sothe = dg.sothe });
        }
    }
}

Thuvien/Areas/Admin/Views/Docgia/Deltai.cshtml
@{
    ViewBag.Title = "Deltai";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@model ThuVien.Models.docgia

<section class="content-header">
    <h1>
        Deltail
        <small>advanced @Model.tendocgia</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Độc giả</a></li>
        <li class="active">Deltail</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="row">
                <div class="col-md-3">

                    <!-- Profile Image -->
                    <div class="box box-primary">
                        <div class="box-body box-profile">
                            <img class="profile-user-img img-responsive img-circle" src="~/Images/docgia/@Model.imgurl" alt="User profile picture">

                            <h3 class="profile-username text-center">@Model.tendocgia <small> @Model.loaidocgia.tenloai</small></h3>

                            @if (Model.gioitinh == true)
                            {
                                <p class="text-muted text-center"><i class="fa fa-mars"></i> Nam</p>
                            }
                            else
                            {
                                <p class="text-muted text-center"><i class="fa fa-mars-stroke"></i> Nữ</p>
                            }

                            <ul class="list-group list-group-unbordered">
                                <li class="list-group-item">
                                    <b>Ngày sinh</b> <a class="pull-right">@string.Format("{0:dd-MM-yyyy}", Model.ngaysinh)</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Địa chỉ</b> <a class="pull-right">@Model.diachi</a>
                                </li>
                                <li class="list-group-item">
                                    <b>SDT</b> <a class="pull-right">@Model.sdt</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Ngày lập</b> <a class="pull-right">@string.Format("{0:dd-MM-yyyy}", Model.ngaythem)</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Hạn thẻ</b> <a class="pull-right">@string.Format("{0:dd-MM-yyyy}", Model.hanthe)</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Thời gian còn lại của thẻ</b>
                                    <a class="pull-right">
                                        @ViewBag.ngayconlai
                                    </a>
                                </li>
                            </ul>

                            <button title="Sửa @Model.tendocgia" type="button" class="col-lg-4 pull-right btn btn-success btn-sm fa fa-pencil-square-o" data-toggle="modal" data-target="#myModal" onclick="return _getById('@Model.sothe');"> cập nhập</button>
                        </div>
                        <!-- /.box-body -->
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs">
                            @*<li ><a href="#activity" data-toggle="tab">Giới thiệu</a></li>*@
                            <li class="active"><a href="#timeline" data-toggle="tab">phiếu mượn</a></li>
                            @*<li><a href="#settings" data-toggle="tab">Settings</a></li>*@
                        </ul>
                        <div class="tab-content">
                            @*<div class=" tab-pane" id="activity">

                            </div>*@
                            <!-- /.tab-pane -->
                            <div class="active tab-pane" id="timeline">

                                <table id="example2" class="table table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>Mã phiếu</th>
                                            <th>Ngày mượn</th>
                                            <th>Trạng thái</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>                  
                                       @{
                                           foreach (var item in Model.muontras)
                                           {
                                            <tr>
                                                <td>@item.maphieu</td>
                                                <td>@item.ngaymuon</td>
                                                <td>
                                                    @if (item.trangthai == true)
                                                    {
                                                        <label class="label label-success">đã trả</label>
                                                    }
                                                    @if (item.trangthai == false)
                                                    {
                                                        <label class="label label-danger">chưa trả</label>
                                                    }
                                                </td>
                                                <td><a href="@Url.Action("Deltai","Muontra",new { id=item.maphieu})" class="btn btn-info fa fa-info-circle"></a></td>
                                            </tr>
                                           }
                                    }

                                    </tbody>
                                </table>


                            </div>
                            <!-- /.tab-pane -->
                            <!-- /.tab-pane -->
                        </div>
                        <!-- /.tab-content -->
                    </div>
                    <!-- /.nav-tabs-custom -->
                </div>
                <!-- /.col -->
            </div>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>



<div class="modal fade" id="myModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            @using (Html.BeginForm("Edit", "Docgia", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return _error()" }))
            {
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Sửa thông tin</h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" id="sothe" name="sothe" />
                    <label>Loại độc giả</label>
                    @Html.DropDownList("maloaidocgia", null, htmlAttributes: new { @class = "form-control" })
                    <label>Tên độc giả</label>
                    <input type="text" id="tendocgia" name="tendocgia" class="form-control" />
                    <label class="label label-danger" id="er_tendocgia"></label>
                    <br />
                    <label>Ngày sinh</label>
                    <input type="date" id="ngaysinh" name="ngaysinh" value="@string.Format("{0:yyyy-MM-dd}", Model.ngaysinh)" class="form-control" />
                    <label class="label label-danger" id="er_ngaysinh"></label>
                    <br />
                    <label>Địa chỉ</label>
                    <input type="text" id="diachi" name="diachi" class="form-control" />
                    <label class="label label-danger" id="er_diachi"></label>
                    <br />
                    <label>Số điện thoại</label>
                    <input type="text" id="sdt" name="sdt" class="form-control" />
                    <label class="label label-danger" id="er_sdt"></label>
                    <br />
                    <label>Giới tính</label><br />
                    <select name="gioitinh" class="form-control">
                        <option value="true" @ViewBag.nam>Nam</option>
                        <option value="false" @ViewBag.nu>Nữ</option>
                    </select>
                    <br />

                    <label>Ảnh đại diện</label>
                    <input type="file" id="imgurl" name="imgurl" class="form-control" />
                    <label class="label label-danger" id="er_imgurl"></label>
                    <br />
                    <label>Trạng thái</label>
                    <select name="trangthai" class="form-control">
                        <option value="true" @ViewBag.active>active</option>
                        <option value="false" @ViewBag.block>block</option>
                    </select>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button type="submit" id="btnAdd" class="btn btn-primary">Save changes</button>
                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
<script src="~/scripts/docgia.js"></script>

Thuvien/Areas/Admin/Views/Docgia/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<ThuVien.Models.docgia>

<section class="content-header">
    <h1>
        Độc giả
        <small>advanced độc giả</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        @*<li><a href="#">Tables</a></li>*@
        <li class="active">độc giả</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
                        Thêm mới
                    </button>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Số thẻ</th>
                                <th>Tên độc giả</th>
                                <th>Loại độc giả</th>
                                <th>Ngày sinh</th>
                                <th>Địa chỉ</th>
                                <th>Số điện thoại</th>
                                <th>Tiền thẻ</th>
                                <th>Ảnh đại diện</th>
                                <th>Trạng thái</th>

                                <th>Option</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.sothe</td>
                                        <td>@item.tendocgia</td>
                                        <td>@item.loaidocgia.tenloai</td>
                                        <td>@item.ngaysinh</td>
                                        <td>@item.diachi</td>
                                        <td>@item.sdt</td>
                                        <td>
                                            <ul class="pagination">                                    
                                                <li class="active"><a href="#">@double.Parse(item.tienthe.ToString()).ToString("#,##0")</a></li>
                                                <li><button class="btn btn-info" onclick="return Naptien('@item.sothe')"><i class="fa fa-plus-square-o"></i></button></li>
                                            </ul>
                                        </td>
                                        <td><img class="profile-user-img img-responsive img-circle" src="~/Images/docgia/@item.imgurl" alt="User profile picture"></td>
                                        <td>
                                            @if (item.trangthai == true)
                                            {
                                                <label class="label label-success">active</label>
                                            }
                                            @if (item.trangthai == false)
                                            {
                                                <label class="label label-danger">block</label>
                                            }
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Deltai","Docgia",new { sothe=item.sothe})" class="btn btn-sm btn-info fa fa-eye"></a>
                                            <button onclick="return _delete('@item.sothe');" class="btn btn-danger btn-sm fa fa-times"></button>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
@*<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>*@

<div id="myModalcart" class="modal fade" role="dialog">
    <div class="modal-dialog modal-sm">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Cập nhập số tiền</h4>
            </div>
            <div class="modal-body">
                <input type="hidden"  id="sothe_up" />
                <label>Nhập số tiền</label>
                <input type="number" class="form-control" id="update_cart" />
                <label class="label label-danger"id="er_update_cart"></label>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                <button type="button" onclick="return _naptien()" class="btn btn-success pull-right">cập nhập</button>
            </div>
        </div>

    </div>
</div>

<div class="modal fade" id="myModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            @using (Html.BeginForm("Create", "Docgia", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return _error()" }))
            {
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Default Modal</h4>
                </div>
                <div class="modal-body">
                    <label>Loại độc giả</label>
                    @Html.DropDownList("maloaidocgia", null, htmlAttributes: new { @class = "form-control" })
                    <label>Tên độc giả</label>
                    <input type="text" id="tendocgia" name="tendocgia" class="form-control" />
                    <label class="label label-danger" id="er_tendocgia"></label>
                    <br />
                    <label>Ngày sinh</label>
                    <input type="date" id="ngaysinh" name="ngaysinh" class="form-control" />
                    <label class="label label-danger" id="er_ngaysinh"></label>
                    <br />
                    <label>Địa chỉ</label>
                    <input type="text" id="diachi" name="diachi" class="form-control" />
                    <label class="label label-danger" id="er_diachi"></label>
                    <br />
                    <label>Số điện thoại</label>
                    <input type="text" id="sdt" name="sdt" class="form-control" />
                    <label class="label label-danger" id="er_sdt"></label>
                    <br />
                    <label>Giới tính</label><br />
                    <select name="gioitinh" class="form-control">
                        <option value="">not set</option>
                        <option value="true">Nam</option>
                        <option value="false">Nữ</option>
                    </select>
                    <br />

                    <label>Ảnh đại diện</label>
                    <input type="file" id="imgurl" name="imgurl" class="form-control" />
                    <label class="label label-danger" id="er_imgurl"></label>
                    <br />
                    <label>Trạng thái</label>
                    <select name="trangthai" class="form-control">
                        <option value="true">active</option>
                        <option value="false">block</option>
                    </select>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button type="submit" id="btnAdd"  class="btn btn-primary">Save changes</button>
                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
<script src="~/scripts/docgia.js"></script>